[package]
name = "demo"
version = "0.0.1"
authors = ["doylecnn"]
links = "CQP"
build = "build.rs"

[dependencies.cqpsdk]
git = "https://github.com/doylecnn/cqpsdk-rust"

[dependencies]
encoding = "0.2"
lazy_static="*"
serde_json = "*"

[lib]
name = "demo"
crate-type = [ "dylib" ]